name: Publish
on:
  push:
    tags:
      - 'v*'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build & push backend
        run: |
          docker build -t rakshash-backend ./backend
          docker tag rakshash-backend ${{ secrets.DOCKER_USERNAME }}/rakshash-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/rakshash-backend:latest
      - name: Build & push frontend
        run: |
          docker build -t rakshash-frontend ./frontend
          docker tag rakshash-frontend ${{ secrets.DOCKER_USERNAME }}/rakshash-frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/rakshash-frontend:latest
